# Check out Dependabot at: https://github.com/dependabot

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: '05:00'
    assignees:
      - ericcornelissen
    labels:
      - dependencies
    groups:
      stryker:
        patterns:
          - '@stryker-mutator/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: '05:00'
    assignees:
      - ericcornelissen
    labels:
      - dependencies
