name: Audit
on:
  pull_request:
    paths:
      - .github/workflows/audit.yml
      - .nsprc
      - package-lock.json
  push:
    branches:
      - main
      - v3

permissions: read-all

jobs:
  audit:
    name: Audit
    uses: ./.github/workflows/reusable-audit.yml
