name: Config
on:
  pull_request:
    paths:
      - .github/workflows/check-config.yml
      - .github/codecov.yml
      - knip.json
      - package-lock.json
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-config.yml
      - .github/codecov.yml
      - knip.json
      - package-lock.json

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Validate Codecov configuration
        uses: ericcornelissen/codecov-config-validator-action@2a3c15afd02496b4c6f5366166e4e0f610465030 # v1.0.0
  knip:
    name: Knip
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Validate Knip configuration
        run: node scripts/json-schema-validation.js knip.json
