name: Config
on:
  pull_request:
    paths:
      - .github/workflows/check-config.yml
      - .github/codecov.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-config.yml
      - .github/codecov.yml

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Validate Codecov configuration
        uses: ericcornelissen/codecov-config-validator-action@2a3c15afd02496b4c6f5366166e4e0f610465030 # v1.0.0
