name: Nightly
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    name: Audit (${{ matrix.ref }})
    uses: ericcornelissen/eslint-plugin-top/.github/workflows/reusable-audit.yml@main
    strategy:
      matrix:
        ref:
          - main
          - v0
    with:
      ref: ${{ matrix.ref }}
  sast:
    name: SAST
    uses: ericcornelissen/eslint-plugin-top/.github/workflows/reusable-sast.yml@main
    permissions:
      contents: read
      security-events: write
    with:
      ref: main
