name: Release
on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Update type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions: read-all

jobs:
  initiate:
    name: Initiate
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Create automation token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: automation-token
        with:
          client-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Bump version
        env:
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: npm version "$UPDATE_TYPE" --no-git-tag-version
      - name: Update CHANGELOG
        run: node scripts/bump-changelog.js
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.automation-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -B "release-${UPDATE_TYPE}"
          git add CHANGELOG.md package.json package-lock.json
          git commit --message 'Version bump'

          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPOSITORY}"
          git push --force origin "release-${UPDATE_TYPE}"

          gh pr create \
            --base='main' --head="release-${UPDATE_TYPE}" \
            --title="New ${UPDATE_TYPE} release" \
            --body='_This Pull Request was created automatically_

          ---

          ### Merge checklist

          - [ ] All continuous integration checks passed.
          - [ ] The version number is consistently updated in `package.json` and `package-lock.json`.
          - [ ] A new release is added to `CHANGELOG.md` with the correct version number and date.
          - [ ] The new version number is in accordance with [Semantic Versioning].
          - [ ] There are no unexpected changes in the Pull Request.

          ---

          ### Post-merge checklist

          - [ ] The new version is published to [npm].
          - [ ] The `v3` branch is at the merge commit.
          - [ ] There is a git tag for the new version on the merge commit.

          [npm]: https://www.npmjs.com/package/@ericcornelissen/eslint-plugin-top
          [semantic versioning]: https://semver.org/spec/v2.0.0.html'
