name: SAST
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ inputs.ref }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@86f3159a697a097a813ad9bfa0002412d97690a4
        with:
          config-file: ./.github/codeql.yml
          languages: javascript
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@86f3159a697a097a813ad9bfa0002412d97690a4
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Perform GitLeaks analysis
        uses: gitleaks/gitleaks-action@5b07ceca8a89dc14d2191f4a202bd28fae3e76ad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
