name: Audit
on:
  workflow_call:
    inputs:
      refs:
        default: '[""]'
        required: false
        type: string

permissions: read-all

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install Node.js dependencies
        run: npm ci
      - name: Audit all npm dependencies
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: npm run audit
      - name: Audit production npm dependencies
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: npm run audit -- --production
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@5425999620c418539c61a8143f29e346d5f6cf08
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
