name: Secrets
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: ~

permissions: read-all

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@ef410873f2920aafc149c6cbbb5001133cffccba # v3.78.0
        with:
          extra_args: --only-verified
