name: Tooling
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: ~

permissions: read-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
      - name: Create automation token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: automation-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Update tooling
        uses: ericcornelissen/tool-versions-update-action/pr@040e69dec221145526b552d9a74e410851aaed23 # v1.1.3
        with:
          assignees: ericcornelissen
          labels: dependencies
          max: 1
          pr-body: |
            Bumps {{updated-tools}} from {{updated-old-versions}} to {{updated-new-versions}}.

            ---

            _This Pull Request was generated using the [tool-versions-update-action]._

            [tool-versions-update-action]: https://github.com/ericcornelissen/tool-versions-update-action
          pr-title: Bump {{updated-tools}} from {{updated-old-versions}} to {{updated-new-versions}}
          token: ${{ steps.automation-token.outputs.token }}
